---

Description: Application Stack Setup
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Description: Environment name
    Type: String
  KeyName:
    Type: String
  AppImageID:
    Type: String
  Region:
    Type: String
  TemplatesBucket:
    Type: String

Resources:
  Foundation:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        Environment:
          Ref: Environment
        Region:
          Ref: Region
      TemplateURL:
        Fn::Join:
          - ""
          -
            - https://s3.amazonaws.com/
            - Ref: TemplatesBucket
            - foundation.yml
      TimeoutInMinutes: 5

  Datastorage:
    DependsOn:
      - Foundation
    Type: "AWS::CloudFormation::Stack"
    Properties:
      Parameters:
        Environment:
          Ref: Environment
        SubnetPublicA:
          Fn::GetAtt:
            - Foundation
            - Outputs.SubnetPublicA
        SubnetPublicB:
          Fn::GetAtt:
            - Foundation
            - Outputs.SubnetPublicB
        SubnetPublicC:
          Fn::GetAtt:
            - Foundation
            - Outputs.SubnetPublicC
        VpcID:
          Fn::GetAtt:
            - Foundation
            - Outputs.VpcID
      TemplateURL:
        Fn::Join:
          - ""
          -
            - https://s3.amazonaws.com/
            - Ref: TemplatesBucket
            - datastorage.yml
      TimeoutInMinutes: 30

  App:
    Type: "AWS::CloudFormation::Stack"
    DependsOn:
      - Foundation
      - Datastorage
    Properties:
      Parameters:
        AppImageID:
          Ref: AppImageID
        DatastoreAddress:
          Fn::GetAtt:
            - Datastorage
            - Outputs.Address
        Environment:
          Ref: Environment
        KeyName:
          Ref: KeyName
        VpcID:
          Fn::GetAtt:
            - Foundation
            - Outputs.VpcID
      TemplateURL:
        Fn::Join:
          - ""
          -
            - https://s3.amazonaws.com/
            - Ref: TemplatesBucket
            - app.yml
      TimeoutInMinutes: 20
