---
Description: Application Stack Setup
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AppImageID:
    Type: String
  AppInstanceType:
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
    ConstraintDescription: must be a valid RDS instance type.
    Default: t2.small
    Description: App instance type
    Type: String
  DatastoreAddress:
    Type: String
  Environment:
    Description: Environment name
    Type: String
  KeyName:
    Type: String
  PublicSubnet:
    Type: String
  VpcID:
    Type: String

Resources:
  AppSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable access to application
      VpcId:
        Ref: VpcID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          # Open to entire world
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          # Open to entire world
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value:
            Fn::Join:
              - "-"
              -
                - Ref: Environment
                - app

  AppEc2:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType:
        Ref: AppInstanceType
      ImageId:
        Ref: AppImageID
      KeyName:
        Ref: KeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId:
            Ref: PublicSubnet
      SecurityGroups:
        - Ref: AppSg
      UserData:
        Fn::Base64:
          Fn::Join:
            - ''
            -
              - "#!/bin/bash\n"
              - /my/script.sh '
              - Ref: DatastoreAddress

Outputs:
  AppDNS:
    Value:
      Fn::GetAtt:
        - AppEc2
        - PublicDnsName
  AppIP:
    Value:
      Fn::GetAtt:
        - AppEc2
        - PublicIp
